name:                         Rust test

on:
  pull_request:
  push:
    branches:
      - master
      - stable

jobs:
  check:
    name:                     Cargo nextest
    runs-on:                  ubuntu-latest
    steps:

      - name:                 Cancel Previous Runs
        uses:                 styfle/cancel-workflow-action@bb6001c4ea612bf59c3abfc4756fbceee4f870c7 # 0.10.0
        with:
          access_token:       ${{ github.token }}

      - name:                 Checkout sources
        uses:                 actions/checkout@v3
        with:
          fetch-depth:        50
          submodules:         'recursive'

      - name:                 Install Rust stable toolchain
        uses:                 actions-rs/toolchain@v1.0.7
        with:
          profile:            minimal
          toolchain:          stable
          override:           true

      - name:                 Install cargo-nextest
        uses:                 baptiste0928/cargo-install@bf6758885262d0e6f61089a9d8c8790d3ac3368f # v1.3.0
        with:
          crate:              cargo-nextest
          version:            0.9

      - name:                 Rust Cache
        uses:                 Swatinem/rust-cache@6720f05bc48b77f96918929a9019fb2203ff71f8 # v2.0.0
        with:
          working-directory:  .

      - name:                 cargo nextest
        run:                  cargo nextest run --retries 2
